# Generated by Django 4.2 on 2023-05-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("game_time", models.FloatField(default=0)),
            ],
        ),
    ]
